apiVersion: v1
kind: ReplicationController
metadata:
    name: nginx-v1
    spec:
        replicas: 2
            selector:
                  app: nginx
                      template:
                            name: nginx
                                  namespace: webenv
                                        metadata:
                                                labels:
                                                          app: nginx
                                                                spec:
                                                                        containers:
                                                                                - name: nginx
                                                                                          image: nginx
